<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f"%>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h"%>

<html xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/jsf/core ">
<head>
    <title>Richfaces/Native File Upload</title>
</head>

<body>
<f:view>
    <h:form enctype="multipart/form-data">
        <h:panelGrid columns="1" cellpadding="2" cellspacing="2" styleClass="sectionHeaderTable">

                <h:outputText value="#{processDatFileBean.displayMessage}" rendered="#{processDatFileBean.errors == null}" styleClass="errorText" id="AutoGeneratedId_11877936128431"/>
        </h:panelGrid>
    </h:form>
</f:view>
</body>
</html>