<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f"%>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h"%>

<html xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/jsf/core ">
<head>
    <title>Commons File Upload</title>
</head>

<body>
<f:view>
    <h:form enctype="multipart/form-data">
        <h:panelGrid columns="2" cellpadding="2" cellspacing="2" styleClass="sectionHeaderTable">
            <h:panelGrid columns="1" rendered="#{selectedExamBean.selectedExam != null and selectedExamBean.exam.rowCount > 0}" styleClass="sectionHeaderTable" width="100%" cellpadding="4" cellspacing="4">
                <f:verbatim>
                    <input type="file" name="textfile"/>
                </f:verbatim>
                <h:outputText id="friendlyMsg" value="File to upload can be found at: c:\\cetarsanswers\\exam.dat or" styleClass="uploadText"/>
                <h:outputText id="friendlyMsg2" value="c:\\Users\\Public\\Documents\\cetarsanswers\\exam.dat" styleClass="uploadText"/>
            </h:panelGrid>

            <h:panelGrid rendered="#{selectedExamBean.selectedExam != null}" id="inventory_1000" columns="2" styleClass="sectionHeaderTable" width="100%" cellpadding="0" cellspacing="0">
                <h:panelGrid columns="1" cellpadding="4" cellspacing="4">
                    <h:commandButton disabled="#{selectedExamBean.selectedExam == null or selectedExamBean.exam.rowCount < 1}" id="inventory_1400" value="Upload And Save" action="#{processDatFileBean.uploadFile}"/>
                    <h:commandButton disabled="#{not processDatFileBean.uploadSuccessful}" value="Review Grades" action="#{selectedExamBean.review}" id="AutoGeneratedId_11877936128430"/>
                    <h:commandButton disabled="#{selectedExamBean.selectedExam == null}" id="cnx" value="Cancel" action="#{processDatFileBean.cancel}"/>
                </h:panelGrid>
                <h:outputText value="#{processDatFileBean.displayMessage}" rendered="#{processDatFileBean.errors == null}" styleClass="errorText" id="AutoGeneratedId_11877936128431"/>
                <h:dataTable id="errs"
                             value="#{processDatFileBean.errors}"
                             var="cur"
                             columnClasses="leftJustified"
                             rendered="#{processDatFileBean.errors != null}">
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Errors" styleClass="columnHeaderText"/>
                        </f:facet>
                        <h:outputText value="#{cur}" styleClass="errorText"/>
                    </h:column>
                </h:dataTable>
            </h:panelGrid>
        </h:panelGrid>
    </h:form>
</f:view>
</body>
</html>